Timestamps refactor
farm-ng/farm-ng-amiga pull request #121
Opened 2023-07-17 22:10 UTC by Hackerman342

2023-07-18 06:20 UTC, ethanrublee requested changes

2023-07-18 06:20 UTC, ethanrublee commented on protos/farm_ng/oak/oak.proto
> +  double timestamp_host = 7;   // seconds, host receive time in monotonic clock
i would call this ``timestamp_recv``.

2023-07-18 06:20 UTC, ethanrublee commented on protos/farm_ng/oak/oak.proto
> +  double timestamp = 4;        // seconds, capture time device monotonic clock
The comment here is wrong.  This is the timestamp, on the host's monotonic clock, when the image was captured (the beginning of the exposure).  Note this timestamp is not monotonic as the timestamp is synchronized with the host. 

References:
https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/sync_frames/#frame-capture-graphs
https://github.com/luxonis/depthai/issues/214

timestamp_device is the device's monotonic clock, beginning of the exposure and is monotonic.

2023-07-18 06:20 UTC, ethanrublee commented on protos/farm_ng/oak/oak.proto
> +  double timestamp_host = 6;   // See OakImageMeta
timestamp_recv

2023-07-18 06:20 UTC, ethanrublee commented on protos/farm_ng/oak/oak.proto
> +  double timestamp_host = 6;   // See OakImageMeta
timestamp_recv

2023-07-18 20:46 UTC, ethanrublee approved these changes

2023-07-18 22:44 UTC, Hackerman342 commented on protos/farm_ng/gps/gps.proto
> +    farm_ng.core.proto.Timestamp gps_time = 14;  // ITOW (integer time of the week) on the device
Change comment if reference clock of `gps_time` is set to change

2023-07-18 22:44 UTC, Hackerman342 commented on protos/farm_ng/gps/gps.proto
> +  farm_ng.core.proto.Timestamp gps_time = 2; // ITOW (integer time of the week) on the device
Change comment if reference clock of gps_time is set to change

2023-07-19 08:46 UTC, edgarriba approved these changes

2023-07-19 08:47 UTC, edgarriba commented on protos/farm_ng/gps/gps.proto
> +    farm_ng.core.proto.Timestamp gps_time = 14;  // ITOW (integer time of the week) on the device
`stamp` in line 62 i feel we should give a more specific name

2023-07-19 14:25 UTC, Hackerman342 commented on protos/farm_ng/gps/gps.proto
> +    farm_ng.core.proto.Timestamp gps_time = 14;  // ITOW (integer time of the week) on the device
Let's save some refactoring of the GPS service & redefining the protos to better match the ubx messages for its own PR

2023-07-19 14:33 UTC, merged