lock req versions + release 2.3.3
farm-ng/farm-ng-amiga pull request #224
Opened 2024-12-11 23:08 UTC by MScatolin

2024-12-12 20:40 UTC, mihelich requested changes

2024-12-12 20:40 UTC, mihelich commented on setup.cfg
> +    protobuf==4.23.4
Same comment as https://github.com/farm-ng/farm-ng-core/pull/261#discussion_r1882841150. I thought we would pin `5.27.x`?

2024-12-12 20:46 UTC, mihelich commented on setup.cfg
> +    protobuf==4.23.4
I.e. what was proposed in #220.

2024-12-13 18:15 UTC, MScatolin commented on setup.cfg
> +    protobuf==4.23.4
changed to protobuf<=5.72.5 and unlocked grpcio and grpcio-tools.

2024-12-13 19:51 UTC, ianBtesser approved these changes

2024-12-13 20:46 UTC, mihelich approved these changes

2024-12-18 16:27 UTC, merged