Update file reader example
farm-ng/farm-ng-amiga pull request #44
Opened 2022-11-28 15:07 UTC by edgarriba

depends on https://github.com/farm-ng/farm-ng-core/pull/47

2022-11-28 15:15 UTC, Hackerman342 approved these changes
LGTM

2022-11-28 15:15 UTC, Hackerman342 commented on py/examples/file_reader/main.py
>      uri: uri_pb2.Uri = uris[1]
I think you'd talked of removing this hard coded value

2022-11-28 15:51 UTC, ethanrublee commented on py/examples/file_reader/main.py
> +        sample = reader.read_message(event_log)
In c++ the event_log_pos wrapper has a read function which allows for a little less boilerplate here, especially when reading multiple event logs simultaneously

2022-11-29 15:58 UTC, ethanrublee requested changes
The hard coded value in Uris is difficult to debug, just ran into it last night. Would be best to fix.

2022-11-29 20:10 UTC, ethanrublee approved these changes

2022-11-29 21:43 UTC, merged