added feature request form
farm-ng/farm-ng-amiga pull request #50
Opened 2022-12-19 20:13 UTC by jerrycowell96

2022-12-19 21:38 UTC, edgarriba requested changes

2022-12-19 21:38 UTC, edgarriba commented on .github/ISSUE_TEMPLATE/feature-request.md
> +- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.
Update this

2022-12-19 21:49 UTC, edgarriba approved these changes

2022-12-23 02:14 UTC, ethanrublee approved these changes

2022-12-23 07:46 UTC, merged